---
services:
  event-platform-api:
    container_name: event-platform-api
    restart: always
    build:
      dockerfile: Dockerfile
    image: event-platform-api:latest
    environment:
      PROFILE: local
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: event_platform
      POSTGRES_PASSWORD: mypwd
      POSTGRES_DB: event_platform
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  localstack:
    container_name: localstack
    ports:
      - "4566:4566"
    image: localstack/localstack
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=123secret
      - AWS_ACCESS_KEY_ID=123secret
      - DEBUG=1
    command: sh ./local/localstack/init-localstack.sh
    volumes:
      - ./local/localstack:/etc/localstack/init/ready.d
      - ./local/localstack/storage:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres:
    driver: local
  localstack:
    driver: local
