---
server:
  port: 8080

spring:
  kafka:
    listener:
      ack-mode: manual_immediate
    consumer:
      bootstrap-servers: localhost:9092
      group-id: ep-1
      auto-offset-reset: earliest
      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/event_platform
    username: event_platform
    password: mypwd

management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: prometheus

event-topic: event_platform

springtools:
  jwt-secret: world
  access-token: world

springdoc:
  api-docs:
    path: /api-docs.yml
  swagger-ui:
    path: /docs
