---

name: Backport para develop

on:
  push:
    branches:
      - master

jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Criar Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: 'backport/${{ github.run_id }}'
          title: 'Backport de alterações para develop'
          body: 'Este PR faz o backport de alterações da master para develop.'
