---
name: backport

on:
  push:
    branches:
      - master

jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create pull request
        run: |
          gh pr create -B develop -H master --title "backport" --body "
          # Backport Pull Request
          This is a backport pull request to sync \`develop\` with \`master\`.
          Close and reopen the pr to run the actions:
          https://github.com/peter-evans/create-pull-request
          "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
