---

name: Sync develop with master

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create a new branch with timestamp
        run: |
          git checkout -b backport

      - name: Push the new branch
        run: |
          git push origin backport

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "backport"
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Sync develop with master"
          pr_body: "Update develop with the latest changes from master."

      - name: Merge Pull Request
        uses: pascalgn/automerge-action@v0.13.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "Merge pull request ({{pullRequest.number}})
           for ({{pullRequest.title}})"
          MERGE_FORKS: "false"
          UPDATE_LABELS: ""
