---
name: backport

on:
  push:
    branches:
      - master

jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create pull request
        run:
          timestamp=$(date +%Y%m%d%H%M%S)
          gh pr create -B develop -H master --title "backport/$timestamp"
          --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
