---

name: Backport to develop

on:
  push:
    branches:
      - master

jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: master
          target_branch: develop
          title: 'backport/${{ github.run_id }}'
          body: "**Automated pull request**"
          get_diff: true
          ignore_users: "dependabot"
          allow_no_diff: false
