---

name: Backport para develop

on:
  push:
    branches:
      - master

jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - name: create pull request
        run: gh pr create -B master -H develop --title 'Backport'
          --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
