name: Sync develop with master

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create a new branch
        run: |
          git checkout -b backport

      - name: Rebase master onto backport branch
        run: |
          git rebase master

      - name: Checkout develop and merge backport branch into develop
        run: |
          git checkout develop
          git merge --no-ff backport
          git push origin develop
