---
name: backport

on:
  push:
    branches:
      - master

jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          title: "backport"
          body: "# Backport Pull Request\nThis
          is a backport pull request to sync `develop` with `master`."
          draft: false
          labels: "backport"
          commit-message: "Sync `develop` with `master`"

      - name: Check output
        run: echo "Pull Request Number -
          ${{ steps.cpr.outputs.pull-request-number }}"
