---
name: Creating release/hotfix tag

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  build-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate branch name
        run: |
          branch_name="${{ github.head_ref }}"
          target_branch_name="${{ github.base_ref }}"
          echo "branch: $branch_name to target branch: $target_branch_name"

          release_pattern="^(release)/[0-9]+.[0-9]+.[0-9]+$"
          hotfix_pattern="^(hotfix)/[0-9]+.[0-9]+.[0-9]+$"

          if [[ "$branch_name" =~ $release_pattern ]]; then
            echo "Release branch detected"
            if [[ "$target_branch_name" != "master" ]]; then
              echo "Release branch must target master"
              exit 1
            fi
          elif [[ "$branch_name" =~ $hotfix_pattern ]]; then
            echo "Hotfix branch detected"
            if [[ "$target_branch_name" != "master" ]]; then
              echo "Hotfix branch must target master"
              exit 1
            fi
          else
            echo "Invalid branch name"
            exit 1
          fi
        shell: bash

      - name: Cache RC number
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.rc_number
          key: ${{ github.head_ref }}

      - name: Extract version from branch name and create rc string
        id: extract_version
        run: |
          branch="${{ github.head_ref }}"
          version=${branch//release\//}
          version=${version//hotfix\//}
          echo "Version: $version"

          # Get current rc number from cache file
          if [ -f ~/.rc_number ]; then
            rc_number=$(cat ~/.rc_number)
          else
            rc_number=0
          fi

          # Increment rc number by 1
          rc_number=$((rc_number + 1))

          # Create rc string
          rc_string="rc-$rc_number"
          echo "RC string: $rc_string"

          # Set output variables using environment files
          echo "version=$version" >> $GITHUB_ENV
          echo "rc_string=$rc_string" >> $GITHUB_ENV

          # Update RC_NUMBER cache file
          echo $rc_number > ~/.rc_number

          echo "$version-$rc_string"
        shell: bash
