---
name: Creating release/hotfix tag

on:
  pull_request:
    branches:
      - release/*
      - hotfix/*
    types: [opened, synchronize]

jobs:
  create_and_increment_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
